updated example plugin to use version 2.0.2 of crate
crate/crate-example-plugin pull request #11
Opened 2017-07-03 12:06 UTC by dornbirndevelops

2017-07-03 13:03 UTC, mikethebeer requested changes
pls squash at the end

2017-07-03 13:03 UTC, mikethebeer commented on src/main/java/io/crate/plugin/ExamplePlugin.java
> +//
pls use the CRATE license header

2017-07-03 13:19 UTC, mikethebeer requested changes

2017-07-03 13:19 UTC, mikethebeer commented on src/test/java/io/crate/operation/scalar/IsEvenScalarFunctionTest.java
> +        assertTrue(isEvenFunction.evaluate((Input<Long>) () -> new Long(evenNumber)));
`assertTrue(isEvenFunction.evaluate((Input<Long>) () -> evenNumber));`

2017-07-03 13:19 UTC, mikethebeer commented on src/test/java/io/crate/operation/scalar/IsEvenScalarFunctionTest.java
> +        try {
remove

2017-07-03 13:45 UTC, mikethebeer requested changes

2017-07-03 13:45 UTC, mikethebeer commented on src/test/java/io/crate/operation/scalar/IsEvenScalarFunctionTest.java
> +        try {
extract into separate test method `testInvalidNumberOfArguments`

2017-07-03 13:54 UTC, mikethebeer commented on src/main/java/io/crate/plugin/ExamplePlugin.java
> + - * Licensed to CRATE Technology GmbH ("Crate") under one or more contributor
pls check `-`

2017-07-03 13:57 UTC, mikethebeer approved these changes
LGTM

2017-07-03 14:00 UTC, merged

2017-07-04 12:25 UTC, seut commented on build.gradle
>      dependency 'net.rtme:classnamerj:0.0.1'
as you replaced the nice classnamer scalar with a boring is_even scalar ;( this dependency is no longer needed.